
# devnet: https://api.devnet.solana.com
# testnet: https://api.testnet.solana.com
# mainnet: https://api.mainnet-beta.solana.com
# localnet: http://127.0.0.1:8899
# debug: http://34.90.18.145:8899

### query account info
POST https://api.testnet.solana.com
content-type: application/json

{
   "jsonrpc": "2.0",
   "id": 1,
   "method": "getAccountInfo",
   "params": [
     "Cq1a7rXyxQWqZbu4FTmNseURU1cXKYMiwZKGe34JKD1",
     {
       "encoding": "jsonParsed"
     }
   ]
}

### get balance
POST https://api.testnet.solana.com
content-type: application/json

{
    "jsonrpc": "2.0", "id": 1,
    "method": "getBalance",
    "params": [
      "3gghk7mHWtFsJcg6EZGK7sbHj3qW6ExUdZLs9q8GRjia"
    ]
}

### req airdrop
POST https://api.testnet.solana.com
content-type: application/json

  {
    "jsonrpc": "2.0", "id": 1,
    "method": "requestAirdrop",
    "params": [
      "3gghk7mHWtFsJcg6EZGK7sbHj3qW6ExUdZLs9q8GRjia",
      2000000000
    ]
  }

### ret tx detail
POST https://api.testnet.solana.com
content-type: application/json

  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getTransaction",
    "params": [
      "3mJXkBgjEGjhWM6pVdTmpeg6VU2yMD9UDX483CN7pm2VKMB5PgKnkMLvSAtKsyb4AvzMXYXVvehLmATK7DuBNBdA",
      "jsonParsed"
    ]
  }
