
@devnet = https://api.devnet.solana.com
@testnet = https://api.testnet.solana.com
@mainnet = https://api.mainnet-beta.solana.com
@localnet = http://127.0.0.1:8899
@debug = http://34.90.18.145:8899
@alchemy = https://solana-devnet.g.alchemy.com/v2/ClRAj3-CPTvcl7CljBv-fdtwhVK-XWYQ

### query account info
# for i in {1..100}; do curl https://api.devnet.solana.com -X POST -H "Content-Type: application/json" -d '{
#     "jsonrpc": "2.0",
#     "id": 1,
#     "method": "getAccountInfo",
#     "params": [
#       "3gghk7mHWtFsJcg6EZGK7sbHj3qW6ExUdZLs9q8GRjia",
#       {
#         "encoding": "jsonParsed"
#       }
#     ]
#   }' ; echo; done

POST {{devnet}}
content-type: application/json

{
   "jsonrpc": "2.0",
   "id": 1,
   "method": "getAccountInfo",
   "params": [
     "8SiQADFfHaMRMx87fyfs9r7bVMUhH5m6uxGuTeuarwo3",
     {
       "encoding": "jsonParsed"
     }
   ]
}

### get balance
POST {{devnet}}
content-type: application/json

{
    "jsonrpc": "2.0", "id": 1,
    "method": "getBalance",
    "params": [
      "6ZD8c7rhKW6HHcS2MSB993kJvfYH6rJFu76ytmStYyFS"
    ]
}

### req airdrop
POST {{alchemy}}
content-type: application/json

  {
    "jsonrpc": "2.0", "id": 1,
    "method": "requestAirdrop",
    "params": [
      "74SqAGc8wHgkwNx2Hqiz1UdKkZL1gCCvsRRwN2tSm8Ny",
      2000000000
    ]
  }

### req airdrop
POST {{alchemy}}
content-type: application/json

  {
    "jsonrpc": "2.0", "id": 1,
    "method": "requestAirdrop",
    "params": [
      "74SqAGc8wHgkwNx2Hqiz1UdKkZL1gCCvsRRwN2tSm8Ny",
      2000000000
    ]
  }

### req getTokenSupply
POST {{devnet}}
content-type: application/json

  {
    "jsonrpc": "2.0", "id": 1,
    "method": "getTokenSupply",
    "params": [
      "6RzHSwJaq1gLiWoKwT4kUuYwAfDGLTawf49npS5hzBiQ"
    ]
  }

### req latest blockhash
# for i in {1..100}; do curl https://api.devnet.solana.com -X POST -H "Content-Type: application/json" -d '{
#     "id":1,
#     "jsonrpc":"2.0",
#     "method":"getLatestBlockhash",
#     "params":[
#       {
#         "commitment":"processed"
#       }
#     ]
#   }' ; echo; done

POST {{devnet}}
content-type: application/json

  {
    "id":1,
    "jsonrpc":"2.0",
    "method":"getLatestBlockhash",
    "params":[
      {
        "commitment":"processed"
      }
    ]
  }

### getSignaturesForAddress
POST {{devnet}}
content-type: application/json

  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getSignaturesForAddress",
    "params": [
      "3gghk7mHWtFsJcg6EZGK7sbHj3qW6ExUdZLs9q8GRjia",
      {
        "limit": 5
      }
    ]
  }

### sendTransaction
POST {{devnet}}
content-type: application/json

  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "sendTransaction",
    "params": [
      "6BHA4PAuZReUfaoZF9BAuXMCo5EiW6v4dPCuDMxmdQm1mQvhiHriY75UxVZWkQCbLUTKCAPQRomDFJN7zLE7NCNByM1tme1RYiMSv1okBvA78hEgi3rPfe2yjAbSLVTfJh5q3V6DedyMX7MQcqY6ZYgMKRGz4x4MoMQw6y5Lwgmo1ApnwHqBbTZxL7FrAeSTFTsFsgsMQSfEegVeTYeia8oUMu93kXMgmLEiTrRe7DEHdSEiMwUfiQEC7hT5zAPdY6K2zBESkybom3236pAosdNV8g6dCsbJhoWPZ"
    ]
  }


### req tx detail
# for i in {1..100}; do curl https://api.devnet.solana.com -X POST -H "Content-Type: application/json" -d '{
#   "jsonrpc": "2.0",
#   "id": 1,
#   "method": "getTransaction",
#   "params": [
#     "2VGvopAP2NinJ48fpPKae9svtHcAYw6K1mUyW2GDyEyW6Dp3mBtTwat1wPfbCnq2G6hkQa8yiQZTf3dEHDWa4erK",
#     "jsonParsed"
#   ]
# }' ; echo; done

POST {{devnet}}
content-type: application/json

  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getTransaction",
    "params": [
      "2z8fyY32WMsxG9rSUBpPh5Sk6e9kkfQfhMu23kzo4kREQmDNue1q4s4Mnvqajs81TcSPGMMmLNvp5ZBgcFqzxTn7",
      "jsonParsed"
    ]
  }

### getSignatureStatuses
# for i in {1..100}; do  curl https://api.devnet.solana.com -X POST -H "Content-Type: application/json" -d '{
#     "jsonrpc": "2.0",
#     "id": 1,
#     "method": "getSignatureStatuses",
#     "params": [
#       [
#         "2VGvopAP2NinJ48fpPKae9svtHcAYw6K1mUyW2GDyEyW6Dp3mBtTwat1wPfbCnq2G6hkQa8yiQZTf3dEHDWa4erK"
#       ],
#       {
#         "searchTransactionHistory": true
#       }
#     ]
#   }' ; echo; done

POST {{devnet}}
content-type: application/json

  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getSignatureStatuses",
    "params": [
      [
        "4Y5jfu36ZaRwcKgfPBb8d9UdSAmex8SYFdxDb5Lhnt11A2sMde7Rrkruda5BBDL7Pu5B86nj8yBVRxXje7gZXAaz"
      ],
      {
        "searchTransactionHistory": true
      }
    ]
  }
