
@devnet = https://api.devnet.solana.com
@testnet = https://api.testnet.solana.com
@mainnet = https://api.mainnet-beta.solana.com
@localnet = http://127.0.0.1:8899
@debug = http://34.90.18.145:8899
@alchemy = https://solana-devnet.g.alchemy.com/v2/ClRAj3-CPTvcl7CljBv-fdtwhVK-XWYQ

### query account info
POST {{devnet}}
content-type: application/json

{
   "jsonrpc": "2.0",
   "id": 1,
   "method": "getAccountInfo",
   "params": [
     "FWyxWofuHJTjt9zvUqGRkY4WojTTCs7rDsrdJz6m29iR",
     {
       "encoding": "jsonParsed"
     }
   ]
}

### get balance
POST {{devnet}}
content-type: application/json

{
    "jsonrpc": "2.0", "id": 1,
    "method": "getBalance",
    "params": [
      "3gghk7mHWtFsJcg6EZGK7sbHj3qW6ExUdZLs9q8GRjia"
    ]
}

### req airdrop
POST {{alchemy}}
content-type: application/json

  {
    "jsonrpc": "2.0", "id": 1,
    "method": "requestAirdrop",
    "params": [
      "3gghk7mHWtFsJcg6EZGK7sbHj3qW6ExUdZLs9q8GRjia",
      2000000000
    ]
  }

### req airdrop
POST {{alchemy}}
content-type: application/json

  {
    "jsonrpc": "2.0", "id": 1,
    "method": "requestAirdrop",
    "params": [
      "74SqAGc8wHgkwNx2Hqiz1UdKkZL1gCCvsRRwN2tSm8Ny",
      2000000000
    ]
  }

### req getTokenSupply
POST {{devnet}}
content-type: application/json

  {
    "jsonrpc": "2.0", "id": 1,
    "method": "getTokenSupply",
    "params": [
      "6RzHSwJaq1gLiWoKwT4kUuYwAfDGLTawf49npS5hzBiQ"
    ]
  }

### req latest blockhash
POST {{devnet}}
content-type: application/json

  {
    "id":1,
    "jsonrpc":"2.0",
    "method":"getLatestBlockhash",
    "params":[
      {
        "commitment":"processed"
      }
    ]
  }

### getSignaturesForAddress
POST {{devnet}}
content-type: application/json

  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getSignaturesForAddress",
    "params": [
      "3gghk7mHWtFsJcg6EZGK7sbHj3qW6ExUdZLs9q8GRjia",
      {
        "limit": 5
      }
    ]
  }

### sendTransaction
POST {{devnet}}
content-type: application/json

  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "sendTransaction",
    "params": [
      "4hXTCkRzt9WyecNzV1XPgCDfGAZzQKNxLXgynz5QDuWWPSAZBZSHptvWRL3BjCvzUXRdKvHL2b7yGrRQcWyaqsaBCncVG7BFggS8w9snUts67BSh3EqKpXLUm5UMHfD7ZBe9GhARjbNQMLJ1QD3Spr6oMTBU6EhdB4RD8CP2xUxr2u3d6fos36PD98XS6oX8TQjLpsMwncs5DAMiD4nNnR8NBfyghGCWvCVifVwvA8B8TJxE1aiyiv2L429BCWfyzAme5sZW8rDb14NeCQHhZbtNqfXhcp2tAnaAT"
    ]
  }


# for i in {1..100}; do curl https://api.devnet.solana.com -X POST -H "Content-Type: application/json" -d '{
#   "jsonrpc": "2.0",
#   "id": 1,
#   "method": "getTransaction",
#   "params": [
#     "2VGvopAP2NinJ48fpPKae9svtHcAYw6K1mUyW2GDyEyW6Dp3mBtTwat1wPfbCnq2G6hkQa8yiQZTf3dEHDWa4erK",
#     "jsonParsed"
#   ]
# }' | jq ; echo; done

### req tx detail
POST {{devnet}}
content-type: application/json

  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getTransaction",
    "params": [
      "2VGvopAP2NinJ48fpPKae9svtHcAYw6K1mUyW2GDyEyW6Dp3mBtTwat1wPfbCnq2G6hkQa8yiQZTf3dEHDWa4erK",
      "json"
    ]
  }

### getSignatureStatuses
POST {{devnet}}
content-type: application/json

  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getSignatureStatuses",
    "params": [
      [
        "2VGvopAP2NinJ48fpPKae9svtHcAYw6K1mUyW2GDyEyW6Dp3mBtTwat1wPfbCnq2G6hkQa8yiQZTf3dEHDWa4erK"
      ],
      {
        "searchTransactionHistory": true
      }
    ]
  }
