[package]
name = "solana_route"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "solana_route"
path = "src/service.rs"

[dependencies]
candid = { version = "0.10" }
ciborium = "0.2.1"
ic-cdk = "0.14"
serde = "1"
serde_json = "^1.0.117"
serde_bytes = "^0.11.14"
ic-cdk-timers = "0.6"
ic-stable-structures = "0.6"
thiserror = "1"
anyhow = "1.0.86"
strum_macros = "0.25.3"
strum = { version = "0.25.0", features = ["derive"] }
sha2 = "0.10"
hex = "0.4"

ic-crypto-ed25519 = { git = "https://github.com/dfinity/ic", package = "ic-crypto-ed25519" }
ic-canisters-http-types = { git = "https://github.com/dfinity/ic", package = "ic-canisters-http-types" }
ic-management-canister-types = { git = "https://github.com/dfinity/ic", package = "ic-management-canister-types" }

ic-solana = { git = "https://github.com/octopus-network/ic-solana/", branch = "feature/token", package = "ic-solana" }

# ed25519-dalek = "2.1"
# ic0 = "0.18.9"
# num-traits = "0.2.17"
# k256 = { git = "https://github.com/altkdf/elliptic-curves", branch = "schnorr_canister", features = [
#     "schnorr",
# ] }

# getrandom = { version = "0.2", features = ["custom"] }


# base64 = "0.22.1"

# serde-big-array = "0.5.1"
# bincode = "1.3.3"
# bs58 = "0.5.1"
# url = "2.5.0"

# log = "0.4"
# ic-log = { git = "https://github.com/octopus-network/canister-sdk.git", branch = "v0.12.x-stablelog" }
# ic-types = "0.7"
# ic-canister-log = "0.2"
# ic-canisters-http-types = { git = "https://github.com/dfinity/ic", package = "ic-canisters-http-types", tag = "release-2024-03-06_23-01+p2p" }
# ic-crypto-ed25519 = { git = "https://github.com/dfinity/ic", package = "ic-crypto-ed25519", tag = "release-2024-03-06_23-01+p2p" }
# ic-management-canister-types = { git = "https://github.com/dfinity/ic", package = "ic-management-canister-types", tag = "release-2024-03-06_23-01+p2p" }
# ic-base-types = { git = "https://github.com/dfinity/ic", package = "ic-base-types", tag = "release-2024-03-06_23-01+p2p" }
# ic-base-types = { git = "https://github.com/dfinity/ic", package = "ic-base-types" }
# ic-ic00-types = { git = "https://github.com/dfinity/ic", package = "ic-ic00-types" }
# omnity_types = { path = "../../types" }
# serde_json = { workspace = true }
# serde = { workspace = true }
# ic-stable-structures = { workspace = true }
# thiserror = { workspace = true }
# anyhow = { workspace = true }
# This patch is needed due to version conflicts around the zeroize crate
# More info: https://github.com/solana-labs/solana/blob/master/Cargo.toml#L514
[patch.crates-io.curve25519-dalek]
git = "https://github.com/solana-labs/curve25519-dalek.git"
rev = "b500cdc2a920cd5bff9e2dd974d7b97349d61464"

[profile.release]
debug = false
lto = true
strip = true
opt-level = 's'

[dev-dependencies]
# pocket-ic = "3.1.0"
ic-crypto-ed25519 = { git = "https://github.com/dfinity/ic", package = "ic-crypto-ed25519" }

# ic-crypto-ed25519 = { git = "https://github.com/dfinity/ic", package = "ic-crypto-ed25519", tag = "release-2024-03-06_23-01+p2p" }
# solana-sdk = "1.18.8"
# anchor-client = "0.30.1"
